apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: smart/auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4001
          env:
            - name: PORT
              value: "4001"
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: smart-config
                  key: JWT_SECRET
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: smart-secrets
                  key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - port: 4001
      targetPort: 4001