apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-config
data:
  JWT_SECRET: "supersecret"
  DOCTOR_URL: "http://doctor-service:4003"
  APPOINTMENT_URL: "http://appointment-service:4004"
  TELEMEDICINE_URL: "http://telemedicine-service:4005"
  NOTIFICATION_URL: "http://notification-service:4006"