apiVersion: v1
kind: Secret
metadata:
  name: smart-secrets
type: Opaque
stringData:
  MONGO_URI_AUTH: "mongodb+srv://smartuser:StrongPass123%21@cluster0.lpgj8zl.mongodb.net/smart-auth?retryWrites=true&w=majority"
  MONGO_URI_PATIENT: "mongodb+srv://smartuser:StrongPass123%21@cluster0.lpgj8zl.mongodb.net/smart-patient?retryWrites=true&w=majority"
  MONGO_URI_DOCTOR: "mongodb+srv://smartuser:StrongPass123%21@cluster0.lpgj8zl.mongodb.net/smart-doctor?retryWrites=true&w=majority"
  MONGO_URI_APPOINTMENT: "mongodb+srv://smartuser:StrongPass123%21@cluster0.lpgj8zl.mongodb.net/smart-appointment?retryWrites=true&w=majority"
  MONGO_URI_PAYMENT: "mongodb+srv://smartuser:StrongPass123%21@cluster0.lpgj8zl.mongodb.net/smart-payment?retryWrites=true&w=majority"