apiVersion: v1
kind: Secret
metadata:
  name: smart-secrets
type: Opaque
stringData:
  MONGO_URI: "MONGO_URI=mongodb+srv://smartuser:StrongPass123!@cluster0.lpgj8zl.mongodb.net/smart-healthcare?retryWrites=true&w=majority
"